pulsedive:
  key: ''
logging:
  path: logs # Full Path to the log directory
  log_level: DEBUG # Log Level: INFO | DEBUG | WARNING | ERROR
  date_format: "%m-%d-%Y %H:%M:%S" # Date format for log messages
  log_format: "%(asctime)-15s [%(levelname)s]: %(message)s" # Log Message Format
